// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sportsplex;

#nullable disable

namespace Sportsplex.Migrations
{
    [DbContext(typeof(SportsplexDbContext))]
    [Migration("20241214171537_UpdatedData")]
    partial class UpdatedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingUser", b =>
                {
                    b.Property<int>("BookerId")
                        .HasColumnType("integer");

                    b.Property<int>("VenueBookerId")
                        .HasColumnType("integer");

                    b.HasKey("BookerId", "VenueBookerId");

                    b.HasIndex("VenueBookerId");

                    b.ToTable("UserBooking", (string)null);
                });

            modelBuilder.Entity("Sportsplex.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Facility")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Rsvps")
                        .HasColumnType("integer");

                    b.Property<string>("SportSpace")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Looking for a well-maintained baseball field for your team’s practice, friendly matches, or community events? Our well-maintained baseball field is just the right size for youth teams, recreational leagues, or small group games.",
                            Facility = "Drakes Creek Park",
                            Image = "https://mainstreetmediatn.com/wp-content/uploads/images/2020-08-03/dd4fab6c064324561e49e8a44eaa6afc.jpg",
                            LocationId = 1,
                            OwnerId = 1,
                            ReservedDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 120,
                            SportSpace = "Baseball Field 1"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Need a soccer field for your team’s practice sessions, friendly matches, or local events? Our soccer field is ideal for youth teams, recreational leagues, or casual play with friends.",
                            Facility = "Drakes Creek Park",
                            Image = "https://themotzgroup.com/wp-content/webpc-passthru.php?src=https://themotzgroup.com/wp-content/uploads/2022/08/Russell-Creek-Park-Complete-5.2-7.jpg&nocache=1",
                            LocationId = 1,
                            OwnerId = 1,
                            ReservedDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 120,
                            SportSpace = "Soccer Field 1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Make a splash with our pool rental! Whether you're planning a private party, hosting swim lessons, or just looking for a refreshing way to spend the day, our clean and well-maintained pool is ready for you.",
                            Facility = "Nashville Pool",
                            Image = "https://swimswam.com/wp-content/uploads/2017/05/Stock-RCC-pool-4.jpg",
                            LocationId = 3,
                            OwnerId = 1,
                            ReservedDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 120,
                            SportSpace = "Pool 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Get your team together and hit the gridiron with our football field rental. Whether it’s practice, a scrimmage, or a community event, our well-kept field is ready for action.",
                            Facility = "Gallatin Football Complex",
                            Image = "https://www.sunshineofficials.com/wp-content/uploads/2017/06/youth-field.jpg",
                            LocationId = 3,
                            OwnerId = 2,
                            ReservedDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 120,
                            SportSpace = "Field 3"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Our basketball court rental is perfect for players of all skill levels. Whether you're running drills, organizing a pickup game, or hosting a small tournament, this court provides a professional and comfortable space for play.",
                            Facility = "Portland Park",
                            Image = "https://d2rzw8waxoxhv2.cloudfront.net/facilities/large/1ce7836979045d923802/1650980224494-333-243.jpeg",
                            LocationId = 4,
                            OwnerId = 2,
                            ReservedDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 120,
                            SportSpace = "Basketball Court 1"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 10,
                            Description = "Enjoy a game of tennis on our top-quality court, perfect for singles or doubles matches.",
                            Facility = "Sunset Sports Complex",
                            Image = "https://brightspotcdn.byu.edu/dims4/default/f6d0944/2147483647/strip/true/crop/4864x3648+304+0/resize/620x465!/quality/90/?url=https%3A%2F%2Fbrigham-young-brightspot-us-east-2.s3.us-east-2.amazonaws.com%2Fdd%2F74%2F6e8ce64942358cee3fddc68cb3ba%2F1806-59-72.jpg",
                            LocationId = 2,
                            OwnerId = 2,
                            ReservedDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 85,
                            SportSpace = "Tennis Court 1"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            Description = "Host your next lacrosse practice or game on our regulation-size field with marked boundaries.",
                            Facility = "Eagle Ridge Park",
                            Image = "https://turftank.com/wp-content/uploads/2022/12/turftank-dimensions-lacrosse-scaled.jpg",
                            LocationId = 3,
                            OwnerId = 2,
                            ReservedDate = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 75,
                            SportSpace = "Lacrosse Field 1"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 7,
                            Description = "Experience a competitive rugby match on our well-maintained grass field with sideline seating.",
                            Facility = "Highland Sports Arena",
                            Image = "https://www.kieferusa.com/wp-content/uploads/2015/09/rugby_Rhisso-Univ-Japan.jpg",
                            LocationId = 4,
                            OwnerId = 3,
                            ReservedDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 90,
                            SportSpace = "Rugby Field 1"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 8,
                            Description = "Play a fast-paced game of pickleball on our professional court designed for all skill levels.",
                            Facility = "Summit Recreation Center",
                            Image = "https://pickleballsuperstore.com/cdn/shop/articles/pickleball_court_dimensions_top_1147x.jpg?v=1642839067",
                            LocationId = 5,
                            OwnerId = 3,
                            ReservedDate = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 60,
                            SportSpace = "Pickleball Court 6"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Host football games or training sessions on our full-size field with marked yard lines.",
                            Facility = "Riverside Sports Grounds",
                            Image = "https://www.visitspacecoast.com/wp-content/uploads/2024/05/Viera-Regional-Park-Football-and-Lacross-Fields.jpg",
                            LocationId = 6,
                            OwnerId = 1,
                            ReservedDate = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 110,
                            SportSpace = "Football Field 2"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Enjoy an exciting soccer match or practice session on our high-quality turf field.",
                            Facility = "Hillside Park",
                            Image = "https://traceup.com/wp-content/uploads/2023/05/shutterstock_1068727478-e1685120725622.jpg",
                            LocationId = 7,
                            OwnerId = 1,
                            ReservedDate = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 95,
                            SportSpace = "Soccer Field 2"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "Perfect for baseball tournaments, practices, and community events on our regulation field.",
                            Facility = "Westwood Recreation Center",
                            Image = "https://www.gallatintn.gov/ImageRepository/Document?documentID=8738",
                            LocationId = 8,
                            OwnerId = 2,
                            ReservedDate = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 130,
                            SportSpace = "Baseball Field 2"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            Description = "Challenge friends or host tournaments on our outdoor basketball court with premium flooring.",
                            Facility = "Downtown Sports Complex",
                            Image = "https://media.thetriibe.com/wp-content/uploads/2024/09/03122123/Basketball-Court-After.jpg",
                            LocationId = 9,
                            OwnerId = 3,
                            ReservedDate = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 105,
                            SportSpace = "Basketball Court 1"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Enjoy lap swimming, lessons, or water aerobics in our temperature-controlled pool.",
                            Facility = "Aqua Center",
                            Image = "https://havegoggleswilltravel.com/images/116/hamdan-sports-complex-training-pool-dubai-panoramic.jpg",
                            LocationId = 10,
                            OwnerId = 3,
                            ReservedDate = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 115,
                            SportSpace = "Swimming Pool 1"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 10,
                            Description = "Play beach  volleyball on our sand-filled court.",
                            Facility = "Seaside Sports Arena",
                            Image = "https://www.sportswestco.com/wp-content/uploads/Montecito-QAD-Corporation-1.jpg",
                            LocationId = 8,
                            OwnerId = 3,
                            ReservedDate = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rsvps = 100,
                            SportSpace = "Volleyball Court 1"
                        });
                });

            modelBuilder.Entity("Sportsplex.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baseball"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Soccer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Swimming"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lacrosse"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Rugby"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pickleball"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Volleyball"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tennis"
                        });
                });

            modelBuilder.Entity("Sportsplex.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingId = 1,
                            Content = "I love Baseball",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingId = 2,
                            Content = "I love Soccer",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            BookingId = 3,
                            Content = "I love Swimming",
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            BookingId = 4,
                            Content = "I love Football",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            BookingId = 5,
                            Content = "I love Basketball",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Sportsplex.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Hendersonville"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Gallatin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nashville"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Portland"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Murfreesboro"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brentwood"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Clarksville"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Franklin"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nolensville"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mount Juliet"
                        });
                });

            modelBuilder.Entity("Sportsplex.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "noahcurryallenpa@gmail.com",
                            Image = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpYf1NgPAHFUAUb_EeeJ6ZS-l_VxhwiPD_1A&s",
                            Uid = "fgikJy5FMVXz3M8t5DkBSzUp64i2",
                            UserName = "Noah"
                        },
                        new
                        {
                            Id = 2,
                            Email = "deramust@gmail.com",
                            Image = "https://store.nana.co/_next/image?url=https%3A%2F%2Fcdn.nana.sa%2Fcatalog%2Flarge%2F8%2F3%2F5%2Fd%2F835d1df68bafe50d5c93e5354af0a33785bc7cac_8697439302229.jpg&w=1200&q=75",
                            Uid = "MJ1mbp0Gm1dnXYqECtMh3PH5dHy2",
                            UserName = "Toren"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Mrthincrisp@example.com",
                            Image = "https://m.media-amazon.com/images/I/814UidWgKOL.jpg",
                            Uid = "ghi789",
                            UserName = "CoolGuyDerek"
                        });
                });

            modelBuilder.Entity("BookingUser", b =>
                {
                    b.HasOne("Sportsplex.Models.User", null)
                        .WithMany()
                        .HasForeignKey("BookerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportsplex.Models.Booking", null)
                        .WithMany()
                        .HasForeignKey("VenueBookerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sportsplex.Models.Booking", b =>
                {
                    b.HasOne("Sportsplex.Models.Category", "Category")
                        .WithMany("Booking")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportsplex.Models.Location", "Location")
                        .WithMany("Booking")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportsplex.Models.User", "User")
                        .WithMany("VenueOwner")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportsplex.Models.Comment", b =>
                {
                    b.HasOne("Sportsplex.Models.Booking", "Booking")
                        .WithMany("Comments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sportsplex.Models.User", "User")
                        .WithMany("Comment")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sportsplex.Models.Booking", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Sportsplex.Models.Category", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Sportsplex.Models.Location", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Sportsplex.Models.User", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("VenueOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
